language: node_js
node_js:
- 11
- 12
- 13
script:
- npm run lint
- npm run build
- npm run test:ci
deploy:
  provider: npm
  tag: dev
  email: $NPM_EMAIL
  api_key:
    secure: $NPM_API_KEY_SECURE
  on:
    tags: true
    branch: master
