language: node_js
node_js:
  - 11
  - 12
  - 13

before_script:
  - commitlint-travis

script:
  - ./scripts/npm_run_time.sh lint
  - ./scripts/npm_run_time.sh build
  - ./scripts/npm_run_time.sh test
  - npm run upload-code-coverage

after_success:
  - scripts/seriesci.sh
