language: node_js
node_js:
  - 11
  - 12
  - 13
script:
  - commitlint-travis
  - ./scripts/npm_run_time.sh lint
  - ./scripts/npm_run_time.sh build
  - ./scripts/npm_run_time.sh test:ci

after_success:
  - scripts/seriesci.sh